# Generated by Django 3.1.7 on 2021-06-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_orderbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbook',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='total',
            field=models.IntegerField(),
        ),
    ]
